### ISSUE TITLE
How to add a Yes or No continue

### ISSUE THREAD

**Issue by benzevl** [alexa/alexa-cookbook#101]
Sorry, I know this is probably totally basic but I've tried to add a yes/no continue to the skill.
Instead of just stopping after delivering skill, I want to add "Would you like another fact? yes or no"
Yes continues to give another and no ends the skill.

Is there a better place i should ask this?

**Comment by franklin-lobb** [comment]
Since this doesn't sound like an issue with the cookbook per se, the [Alexa Developer Forum](https://forums.developer.amazon.com/spaces/23/Alexa+Skills+Kit.html) would be the best source for general help. If you're still having issues, please post there.

**Comment by benzevl** [comment]
i was able to to use another part of the cookbook to piece together what I needed.  And it worked :)
thank you

**Comment by tanyagupta** [comment]
@benzevl could you post what you were able to use ?
