### ISSUE TITLE
Birthday Hotline - Cannot read property 'locale' of undefined

### ISSUE THREAD

**Issue by feiranl2** [alexa/alexa-cookbook#104]
"errorMessage": "RequestId: 773dfb1b-56ff-11e8-b01c-8b1d348c3fd3 Process exited before completing request"

I also attach the Log Output:
START RequestId: 773dfb1b-56ff-11e8-b01c-8b1d348c3fd3 Version: $LATEST
2018-05-13T22:46:25.421Z	773dfb1b-56ff-11e8-b01c-8b1d348c3fd3	TypeError: Cannot read property 'locale' of undefined
    at AlexaRequestEmitter.HandleLambdaEvent (/var/task/node_modules/alexa-sdk/lib/alexa.js:112:38)
    at AlexaRequestEmitter.value (/var/task/node_modules/alexa-sdk/lib/alexa.js: 100:31)
    at exports.handler (/var/task/index.js:19:11)
END RequestId: 773dfb1b-56ff-11e8-b01c-8b1d348c3fd3
REPORT RequestId: 773dfb1b-56ff-11e8-b01c-8b1d348c3fd3	Duration: 250.75 ms	Billed Duration: 300 ms 	Memory Size: 128 MB	Max Memory Used: 81 MB	
RequestId: 773dfb1b-56ff-11e8-b01c-8b1d348c3fd3 Process exited before completing request

Please tell me how to solve this problem, I really appreciate it!

**Comment by franklin-lobb** [comment]
I looked at the code for the birthday hotline and I cannot find any reference in the code to a locale property being read.  Are you testing using a sample event in the Lambda console or are you testing from the developer portal or a device?

**Comment by franklin-lobb** [comment]
closing due to age and that this sample has become outdated and removed.
