### ISSUE TITLE
TestFlow V2

### ISSUE THREAD

**Issue by jquintozamora** [alexa/alexa-cookbook#109]
We are starting to implement TestFlow in our Alexa Skill, but we realise there is no testflow for V2. 
Any ideas when it will be available? Maybe are we missing some documentation for V2? 

Thanks!

**Comment by robm26** [comment]
Hi @jquintozamora! 
TestFlow works fine for SDK V2 or V1 or no SDK.  It treats your code project like a black box and sends it events.
I have a new beta version with several additional features: currently hosted at https://github.com/robm26/testflow/
Let me know any other issues you have.

**Comment by TheDreamSaver** [comment]
Hi @robm26 
It is written in the readme of TestFlow that it supports both Node.JS and Python projects.
I wanted to know if it can be implemented in Java Projects as well?

**Comment by franklin-lobb** [comment]
closing due to age - if you still have questions, please feel free to reopen.
