### ISSUE TITLE
Following instructions doesn't work - Cannot find module 'alexa-sdk'

### ISSUE THREAD

**Issue by OutsourcedGuru** [alexa/alexa-cookbook#110]
It appears that nobody has actually used your README.md to attempt to follow along. If they had, they would see that it doesn't work.

In a nutshell, the instructions suggest to begin with the space facts ASK+Lambda (which does not have a `package.json` which includes what's necessary). The instructions then have the user replace their Lambda's code with that included with the upgrades. The instructions make no mention of `package.json` nor that it should be used.

This of course results in a the `index.js` not having the appropriate dependencies in `node_modules`. Since there is no such thing as an `npm install` feature, it's not possible to simply edit the `package.json` as we normally might on our local workstation.

**Comment by franklin-lobb** [comment]
Which sample are you attempting to use?

**Comment by OutsourcedGuru** [comment]
I must have gone through thirty pages trying to get this going but I'm reasonably certain that [this is the one](https://github.com/alexa/alexa-cookbook/tree/master/display-directive/bodyTemplate) that doesn't understand the workflow.

> Create a Fact Skill
> 
> Build a fact skill using this tutorial

**Comment by franklin-lobb** [comment]
I'll check that tutorial out and see if there are any quick fixes.  It is due for a refresh to use the latest SDK, so I'd rather invest in that update over spending tons of time fixing the current version.

In the meantime, unless you are specifically looking to make a skill for a display (e.g. Echo Show), you can try this tutorial: https://github.com/alexa/skill-sample-nodejs-fact

If you are eager to try the display features out, you can try this one: https://github.com/alexa/skill-sample-nodejs-berry-bash although I'll note it is also due for refresh to use the latest SDK.

**Comment by franklin-lobb** [comment]
I did some investigation and here's the scoop:  the display-directive tutorial is still using v1 of the SDK and fact tutorial is uses as a platform has been converted to v2, so there is no way to easily fix this without updating the display-directive tutorial to use the new SDK.  As such, I will pull this tutorial offline until it can be updated.  I'm sorry you encountered this and I hope to have the updated version available soon.

**Comment by OutsourcedGuru** [comment]
Thanks. I understand that the Echo Spot is a brand-new product and the development-related documentation has some room to catch-up.

It's important that Amazon—if it wants these new products to succeed in the IoT playspace—put the effort into making sure that the early developers can get some traction.

**Comment by OutsourcedGuru** [comment]
> If you are eager to try the display features out, you can try this one: https://github.com/alexa/skill-sample-nodejs-berry-bash although I'll note it is also due for refresh to use the latest SDK.

That's the intent. I hope to get a firm grasp of exactly how to display images on the Echo Spot since I just purchased one. In my mind, it should be more than just a gallery displayer; individual Lambda responses should be able to easily include background graphics.

**Comment by franklin-lobb** [comment]
closing due to age
