### ISSUE TITLE
Wrong link in readme for testing folder in directory

### ISSUE THREAD

**Issue by allysonja** [alexa/alexa-cookbook#122]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current Behavior

Hello! The testing link in your front-page readme goes to the wrong link! It keeps taking me to
https://github.com/alexa/alexa-cookbook/blob/master/testing#title
instead of 
https://github.com/alexa/alexa-cookbook/tree/master/guides/testing.
Thanks!
## Possible Solution
```
// Not required, but suggest a fix/reason for the bug,
// or ideas how to implement the addition or change
```

## Steps to Reproduce (for bugs)
```
// Provide a self-contained, concise snippet of code
// For more complex issues provide a repo with the smallest sample that reproduces the bug
// Including business logic or unrelated code makes diagnosis more difficult
```

## Your Environment

* ASK SDK for Node.js used: x.x.x
* Operating System and version:

## Node.js and NPM Info
* Node.js version used for development:
* NPM version used for development:

**Comment by franklin-lobb** [comment]
link has been updated
