### ISSUE TITLE
MyIntent only Hello? And expects response of population?

### ISSUE THREAD

**Issue by cnpants** [alexa/alexa-cookbook#127]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Other... Please describe: What to say to Alexa, when your intent is only Hello?
</code></pre>

##Intents
I am not sure how will I get that respond from Alexa when my intent is only hello. She would not respond to the population.

**Comment by franklin-lobb** [comment]
Can you reopen this issue if it is still a problem?  When doing so, can you clarify/restate the question?  I'm not clear on the error or problem you're seeing, or if it's an interaction model design question.
