### ISSUE TITLE
can't find Alexa Skills Kit under 'Add Trigers', can't configure function, can't find function code.

### ISSUE THREAD

**Issue by tiancaipipi110** [alexa/alexa-cookbook#128]
I can't find Alexa Skills Kit under 'Add Trigers', can't 'configure function', can't find 'function code'.
The Alexa Skills kit is missing.

**Comment by tiancaipipi110** [comment]
I think there's something wrong with the region in U.S Ohio since I wasn't able to connect to VUI later on. 
Delete the skill entirely and start over, choose U.S Virginia instead worked out.

**Comment by franklin-lobb** [comment]
The Alexa Skills Kit trigger is currently only available in eu-west-1 (Ireland), us-east-1 (N. Virginia), us-west-2 (Oregon) and ap-northeast-1 (Tokyo).
