### ISSUE TITLE
ASK Deploy is asking for vendor id

### ISSUE THREAD

**Issue by myke11j** [alexa/alexa-cookbook#129]
I have created a Skill using `ask new` and now trying to deploy that. I am using 
`ask deploy
`
and it giving error shown in the screenshot
![screenshot from 2018-07-10 11-11-06](https://user-images.githubusercontent.com/12976433/42491426-54bc5cba-8432-11e8-8909-3576f3f3206a.png)

And this, "creating new skill" keeps on going, like forever.
In docs, I cannot find where I need to add vendor id.
Any guidance will be really helpful

**Comment by franklin-lobb** [comment]
were you able to successfully run `ask init`?  That is where the vendor id is mapped to the profile.

**Comment by myke11j** [comment]
@franklin-lobb Yes, I did.
And it redirected me to my developer.amazon.com, where I logged in successfully.
Is it possible that Amazon account I connected with, doesn't have vendor id?
And why do we need to have a vendor id to deploy skill?

**Comment by myke11j** [comment]
Ahh I got it now
Issue was, I wasn't specifying the Profile, and it was using the 'default'
`ask deploy -p <profile_name>` worked

**Comment by ansarisufiyan777** [comment]
`ask deploy -p "Profilename"
`
Profile name should be in a double quote
