### ISSUE TITLE
CreateListItem Example

### ISSUE THREAD

**Issue by clark173** [alexa/alexa-cookbook#14]
Can you add an example of a [CreateListItem](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/access-the-alexa-shopping-and-to-do-lists#createListItem) intent for the [lists](https://github.com/alexa/alexa-cookbook/tree/master/context/lists) tutorial section? I can't seem to get the `POST` right and keep getting `message: null` responses whenever I try to add an item to a list, so an example would be much appreciated.

Thanks!

**Comment by clark173** [comment]
@ajot and @PaulCutsinger I'm assuming the CreateListItem functionality works on the backend, correct? I am yet to find an example of this in practice and am still getting the `message: null` responses. Is there something I am doing incorrectly?

**Comment by franklin-lobb** [comment]
[this demo](https://github.com/alexa/alexa-cookbook/tree/master/feature-demos/skill-demo-list-access) takes related action but does not use CreateListItem. Please reopen this issue if you're still looking for an example (doubtful due to the age of the issue).
