### ISSUE TITLE
404 errors

### ISSUE THREAD

**Issue by AlexandreMinard** [alexa/alexa-cookbook#143]
On https://github.com/alexa/alexa-cookbook
In Table of Contents
Link to javascript cookbook is wrong => https://github.com/alexa/alexa-cookbook/blob/master/src/javascript/alexa-cookbook.js
Link to documentation of the cookbook is also wrong => https://github.com/alexa/alexa-cookbook/blob/master/docs

Good luck for that

**Comment by franklin-lobb** [comment]
I'll take a look.

**Comment by franklin-lobb** [comment]
This was fixed previously, but the issue not closed.  Closing now.
