### ISSUE TITLE
How to extract data from a website and answer user questions

### ISSUE THREAD

**Issue by sukritchakravarty** [alexa/alexa-cookbook#148]
I am trying to create an app in which I will ask alexa to tell me the nearest hospital from my own webpage which contains all the locations of different hospitals and alexa replies to me with the hospital address and how far is it from me.
Can anyone help me in building this in 7 days?

**Comment by franklin-lobb** [comment]
looks like your deadline has passed; hope you were able to work something out.  If you're still looking into this, check out the device location api and perhaps the dynamic location api, as they may support your use case.
