### ISSUE TITLE
Bad link in high-level documentation

### ISSUE THREAD

**Issue by bundito** [alexa/alexa-cookbook#149]
**Describe the bug**
Page https://developer.amazon.com/docs/custom-skills/access-the-alexa-shopping-and-to-do-lists.html has a link in the 3rd paragraph - "code sample and tutorial" - that leads to a 404 page instead of here.

**To Reproduce**
1. Go to ' https://developer.amazon.com/docs/custom-skills/access-the-alexa-shopping-and-to-do-lists.html '
2. Click on 'code sample and tutorial'
3. Scroll down to N/A
4. See error - 404 page

**Expected behavior**
Link should direct here instead

**Environment (please complete the following information):**
 - OS:Linux
 - Browser Vivaldi
 - Version 2.0.1309.37 (Stable channel) (64-bit)

**Additional context**
Nope, just copy-editing and the fact that I'm good at navigating git repos.

**Comment by franklin-lobb** [comment]
looks like this was corrected at some time in the past.  closing...
