### ISSUE TITLE
Set up AWS link is dead - here's the new one

### ISSUE THREAD

**Issue by loispatt** [alexa/alexa-cookbook#155]
**Link to AWS setup page guide is now dead**

**To Reproduce**
1. In Step 1 on this page "https://github.com/alexa/skill-sample-java-quiz-game/blob/master/instructions/2-lambda-function.md",
try the link for "If you don't have an AWS account, check out this quick walkthrough for setting it up." Note that it 404s.

**Expected behavior**
It should open this page instead:
"https://github.com/alexa/alexa-cookbook/blob/master/guides/aws-security-and-setup/set-up-aws.md"

**Environment (please complete the following information):**
 - Windows 10
 - Chrome

**Additional context**
Probably due to cookbook reorganization, and probably affects other pages too.

**Comment by franklin-lobb** [comment]
fixed
