### ISSUE TITLE
Error in LaunchRequest

### ISSUE THREAD

**Issue by RolandOne** [alexa/alexa-cookbook#158]
**Please describe what you are looking for:**
I am trying to go through the basic setup

I have installed but when running the following
node testflow 
node breakfast.txt
node attraction.txt

There is this error that appears when launching
1 LaunchRequest
Error handled: localizationClient.t is not a function
 Original request was {
  "type": "LaunchRequest",
  "locale": "en-US",
  "requestId": "amzn1.echo-api.request.90e15a67-dd2d-4cf2-93bd-7a1234d0139f",
  "shouldLinkResultBeReturned": false,
  "timestamp": "2019-01-14T02:12:55.887Z"
}

But the rest of the intents are successful and execute.

What do I need to do? Help please.

**Comment by K0NRAD** [comment]
there are the localizationClient.t function is missing in the index.js.
replace the LocalizationInterceptor with the following Code and it will work.
```
const LocalizationInterceptor = {
    process(handlerInput) {
        const localizationClient = i18n.use(sprintf).init({
            lng: handlerInput.requestEnvelope.request.locale,
            overloadTranslationOptionHandler: sprintf.overloadTranslationOptionHandler,
            resources: languageStrings,
            returnObjects: true,
        });
        localizationClient.localize = function () {
            const args = arguments;
            let values = [];

            for (var i = 1; i < args.length; i++) {
                values.push(args[i]);
            }
            const value = i18n.t(args[0], {
                returnObjects: true,
                postProcess: 'sprintf',
                sprintf: values
            });

            if (Array.isArray(value)) {
                return value[Math.floor(Math.random() * value.length)];
            } else {
                return value;
            }
        }
        const attributes = handlerInput.attributesManager.getRequestAttributes();
        attributes.t = function (...args) {
            return localizationClient.localize(...args);
        };
    },
};
```

**Comment by franklin-lobb** [comment]
looks to be resolved, so closing. if this is still an issue, please reopen or create a new issue.
