### ISSUE TITLE
Step missing in Proactive Events demo?

### ISSUE THREAD

**Issue by sohanmaheshwar** [alexa/alexa-cookbook#159]
Hello.

I was following the steps in @robm26 's demo to create a Proactive Events Skill. When I execute the script by running `./deploy.sh`, the CloudFormation stack doesn't create. I ran `aws cloudformation describe-stack-events --stack-name PingMe` to get the list of events leading up to the failure and this was the key part: 

```
"ResourceStatus": "CREATE_FAILED", 
            "ResourceType": "AWS::Lambda::Function", 
            "Timestamp": "2019-01-16T10:07:27.989Z", 
            "ResourceStatusReason": "Your access has been denied by S3, please make sure your request credentials have permission to GetObject for ask-samples-us-east-1-region/proactive-events-demo/proactive-events-skill.zip. S3 Error Code: AccessDenied. S3 Error Message: Access Denied (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException; Request ID: 87559948-1976-11e9-9759-3961cd052dc5)", 
            "StackName": "PingMe", 
```

Is there a step missing where we've to add permissions to S3?

**Comment by NunneryDev** [comment]
I am having the same problem

**Comment by franklin-lobb** [comment]
I've corrected the permissions on the lambda function source.  You should be good to go.  Please try again and LMK if the problem persists.

**Comment by sohanmaheshwar** [comment]
Working for me. @NunneryDev try it out now.
