### ISSUE TITLE
404 in documentation

### ISSUE THREAD

**Issue by jezmck** [alexa/alexa-cookbook#16]
In step 7.1 of [Delegate Dialog Directive Sample Project](https://github.com/alexa/alexa-cookbook/blob/master/handling-responses/dialog-directive-delegate/step-by-step/1-voice-user-interface.md) there is a link to [...alexa-cookbook/.../InteractionModel.json](https://github.com/alexa/alexa-cookbook/blob/master/handling-responses/dialog-directive-delegate/speech-assets/InteractionModel.json) which is 404ing.

**Comment by cncoder** [comment]
You can download file to [InteractionModel.json ]( https://github.com/alexa/alexa-cookbook/blob/master/handling-responses/dialog-directive-delegate/sample-nodejs-plan-my-trip/speech-assets/InteractionModel.json).

But I found the file has something wrong, you can see it in [there](https://github.com/alexa/alexa-cookbook/pull/21).

**Comment by JennJin** [comment]
Verified Broken link resolved.
