### ISSUE TITLE
Add College Coach example design export for PDF

### ISSUE THREAD

**Issue by RalfEggert** [alexa/alexa-cookbook#166]
Please add an PDF export for the College Coach example design as well. Just curious how it looks since I have no Adobe XD right now.

**Comment by franklin-lobb** [comment]
checking on this...

**Comment by franklin-lobb** [comment]
A PDF 'preview' has been added: https://github.com/alexa/alexa-cookbook/blob/master/tools/situational-design/college-coach.xd.pdf

**Comment by RalfEggert** [comment]
Thanks @franklin-lobb 

:+1:
