### ISSUE TITLE
Adobe XD says the *.xd files in this project are invalid.  I cannot open them.

### ISSUE THREAD

**Issue by simonkingaby** [alexa/alexa-cookbook#169]
**Describe the bug**
Adobe XD says the *.xd files in this project are invalid.  I cannot open them.

**To Reproduce**
1. Download the *.xd files.
2. Open the *.xd files.
3. See the error in Adobe XD.

**Expected behavior**
I expected the files to open without an error.

**Environment (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version Latest

**Additional context**

**Comment by franklin-lobb** [comment]
I was able to open the files in Version 19.0.22.9 (Starter), although there were linked files which were missing.  I'll follow up on that, however can you confirm your XD version and edition?

**Comment by simonkingaby** [comment]
I'm using 19.0.22.9 (Starter) too.

**Comment by simonkingaby** [comment]
I figured it out.  I recently discovered GIT LFS.  I tried git lfs clone https://github.com/alexa/alexa-cookbook.git, instead of the normal git clone and it pulled the files down properly.  
Thanks.  This issue can be closed.
