### ISSUE TITLE
error while calling it from ask-cli

### ISSUE THREAD

**Issue by coe16b015** [alexa/alexa-cookbook#172]
**Describe the bug**
While trying to access through ask-cli y typing
ask new --url "https://github.com/alexa/alexa-cookbook/tree/master/feature-demos/skill-demo-dialog-delegate.git" 
 It is throwing an error saying that the repository is not found.

**Comment by franklin-lobb** [comment]
the repository url is https://github.com/alexa/alexa-cookbook.git.  Although instead of using `ask new`, I would recommend using `git clone https://github.com/alexa/alexa-cookbook` to download the repo.  then use `cd alexa-cookbook\feature-demos\skill-demo-dialog-delegate` to get to the feature demo's folder.  Once in that folder, you can use `ask deploy` to deploy it.

**Comment by franklin-lobb** [comment]
@coe16b015 Were you able to get this working?

**Comment by coe16b015** [comment]
Yes, 
But I have another request for you. Are there any demos or examples where we use dynamic entities for giving each customer his/her personalized version. Like how we can dynamically write the offers that skill provides for that customer based on his previous choices/requests. If you could please found and share it to me, I will the happiest man.
Also, are examples available on intent chaining and slot value suggestion.

**Comment by franklin-lobb** [comment]
re: Dynamic Entities
There's a demo/sample that uses dynamic entities in the skill-demo-dynamic-entities folder (same parent as the delegate example you previously referenced).  It does not source the data on an individual basis (it does it on a question basis), however if you wanted to maintain personalized lists, then you could store/track that info using persistent attributes. When a new session is detected the values could be loaded and then the dynamic entities directive could be sent with the initial response.

re: intent chaining
I don't know of any of the examples which use intent chaining. I created issue #175 to track that request.

re: slot value suggestion
I'm not sure if I follow what you are asking about here. My understanding of slot value suggestions is that they are provided in the Developer Console when you are editing a slot type. (They appear just below the slot value entry box.) If you mean something else, please let me know.

**Comment by coe16b015** [comment]
Thank you for your response:
Re: Dynamic entities: Dynamic entities can do two things 
1) With the use of dynamic entities, you can augment your skill's predefined static catalogs by allowing your skill to dynamically create new entities in runtime.
2) With dynamic entities, you can create personalized voice experiences, and dynamically enable or disable slot values based on a conversation or user context. 

There are blogs, documentation, code samples/demos for explaining the 1st one. Even I used the code in the cookbook and I was able to implement them in my skill and get good results.
But I see a lot of value can be created to a skill when we use the 2nd one. **Personalized voice experience.**
The question I am asking you is are there any code samples/ demos/video streams/blogs/documentation explaining how we can implement the 2nd second. I will be grateful if you can provide information.   

Re: Intent Chaining: I read the blog explaining how intent chaining can enhance skill accuracy. But the problem here is the content explaining this feature is missing. It redirects to dialog management documentation where a small part of it is about intent passing in the dialog. So can you provide me more documentation/examples/code samples/more explanation regarding the intent chaining? 
Thank you for making this as request num:175

Re: Slot value suggestion: I understood this and thank you

**Comment by franklin-lobb** [comment]
The difference between the two use cases is what values you provide in the dynamic entities directive. In the first case, the values are specific to your skill's content and independent of the particular customer using the skill.  For example, if your skill's content focused around the news which changed every day, you can provide relevant values for the day to every customer who uses your skill.  In the second case, the values provided would be specific to the customer who was using your skill. So the usage is the same, the source would be different.  If you want some sample code around that part, I would check out samples that maintain data specific to a customer.  A good example is the [High Low Game](https://github.com/alexa/skill-sample-nodejs-highlowgame).  It tracks how many times the customer has played the game using persistent attributes. An example which also teaches more about giving your skill memory, is [Module 3 of Cake Walk](https://github.com/alexa/skill-sample-nodejs-first-skill/blob/master/module-3/README.md).

**Comment by coe16b015** [comment]
Thanks,
Another thing which I didn't understand is "what is versioning" update:
I know versions and aliases which are useful in creating different versions like prod, dev, test, etc. and later help us while we want to update the code.
But the update that shows about versioning in the "alexa.design/parity" is different I think so.
If u have any understanding about versioning please explain me and provide me few use cases where and when we can use versioning and how it can be implemented.

PC: You are helping me a lot, Thanks man!

You can find an update about versioning in alexa.design/parity 
versioning : 3/12/2019
Please explain what it means (what is versioning and how can it be used)

**Comment by franklin-lobb** [comment]
Versioning in this case refers to the version of the interaction model. For example if you added a new intent or slot value and then saved it, it would be a new version. Versions are currently only accessible through SMAPI and the CLI.  For example:
`ask api list-model-versions -l en-US --skill-id amzn1.ask.skill.abc...`
and
`ask api get-model -l en-US --model-version 2 --skill-id amzn1.ask.skill.abc...`

**Comment by coe16b015** [comment]
Thanks again! .But with the use of these versions:
What we can do?
how it helps the developers?
Why actually it is introduced?
Please provide me some use cases?(like in which/what cases versioning is used, just to know what are the intents and slots we added extra or any other higher level purpose, we use versioning)

**Comment by franklin-lobb** [comment]
Since a new version is created when you save (and build) your model, should your changes not yield the results you want, you can revert back to an earlier version.  You could also compare two versions to see what's different.

**Comment by coe16b015** [comment]
Thank you so much: 
What are the use cases of intent chaining?
Any examples where and when can intent chaining can be used

**Comment by franklin-lobb** [comment]
Intent chaining allows you to start dialog management from any intent.  My colleague Justin wrote a blog post about [Intent Chaining](https://developer.amazon.com/blogs/alexa/post/9ffdbddb-948a-4eff-8408-7e210282ed38/intent-chaining-for-alexa-skill) which includes some examples as well as how to use it.

**Comment by coe16b015** [comment]
Hey hai! @ Thanks for the help and suggestions. I have a question regarding storing the user data(persistence attributes). I want two use cases to be implemented using dynamo DB:
1- My skill involves only a single person data, the orders he keeps, the user phone number, the user biodata, etc. I want to store all these. How I can do that using persistence attributes. I want code samples if any one of them is available, please provide me. 

2- My skill involves all the members of a family, mother, father, son, daughter, etc. I want to store the data of each one individually in the same skill as the mother has her own data, the father has her own data likewise others. So how to store the multiple user's data in the same skill. How to implement this and if any code samples regarding this use case are available, please provide them.

Thank you!

**Comment by franklin-lobb** [comment]
The High-Low Game shows persistent attributes, which relates to #1: https://github.com/alexa/skill-sample-nodejs-highlowgame

I don't know of any examples for #2, although it would be similar to what you do for #1, just with an additional level of detail. the customer using the skill will need to identify themselves if you want to associate a specific interaction with a given speaker.

for #3, I'm not sure what you are asking.  Yes, you can use DynamoDB. There might be other examples, however the Audio Player skill shows reading/writing to DynamoDB. https://github.com/alexa/skill-sample-nodejs-audio-player/blob/mainline/multiple-streams/lambda/test/ddbController.js

**Comment by LetMyPeopleCode** [comment]
Auto-closing issues over a year old
