### ISSUE TITLE
"ask clone": Cloning a skill throws an error

### ISSUE THREAD

**Issue by coe16b015** [alexa/alexa-cookbook#176]
**Describe the bug**
I am using "ask clone" method to clone a skill which is in the development stage and AWS lambda deployed. When I want to have that skill's model and lambda, I used "ask clone" to clone skill to my local machine. But it throws an error.
 
![Screenshot (258)](https://user-images.githubusercontent.com/50940284/59908429-00d56380-942b-11e9-8082-a1693c032ed2.png)

The error which I got: I uploaded the screenshot of it. Please help me what is wrong with this and how to resolve it.
But for some skills, it is working fine and it had cloned in my local folder. I don't know If there is an issue with ask clone for certain skills and working properly for other skills, What would be the reason for this difference of ask clone working for few skills and not working for others skills

I have installed git, ask and npm and everything properly.

**Comment by franklin-lobb** [comment]
Hi @coe16b015 - this is a known issue with the CLI that is a result of the space in your path.  (The space between Alexa and codes.) From my experience, you can clone the skill in a path without the space and then move the folder to your desired location and it should work normally from there. (If you run into issues after moving it, I'd suggest to move it back until the CLI is fixed.)

**Comment by coe16b015** [comment]
Thanks, it worked, I will follow the procedure you mentioned when I face any issues with the clone command.

**Comment by franklin-lobb** [comment]
glad to hear it!  I hope it'll be fixed soon, so be sure to regularly check for updates to the CLI.
