### ISSUE TITLE
How to troubleshoot the notification not receiving issue

### ISSUE THREAD

**Issue by srinivas-kandula** [alexa/alexa-cookbook#177]
**Please describe what you are looking for:**
We are working on building an notification application and followed the example "skill-demo-proactive-events", the script returns with 200 status code how ever the alexa device is not receiving the notification.  Any pointers to trouble shoot this issue would be helpful.

**Link you used**

**Source of the link**
**Additional context**
We have enabled notification in the skill and also changed the timezone of alexa device to EDT. Request looks like below
`
"referenceId": referenceId,
       "expiryTime": expiryTime.toISOString(),
       "event": {
           "name": "AMAZON.MediaContent.Available",
           "payload": {
               "availability": {
                   "startTime" : startTime.toISOString(),
                   "provider": {
                       "name": "localizedattribute:providerName"
                   },
                   "method": "STREAM"
               },
               "content": {
                   "name": "localizedattribute:contentName",
                   "contentType": "GAME"
               }
           },
       },
       "localizedAttributes": [
           {
               "locale": "en-US",
               "providerName": mediaEventProvider,
               "contentName": mediaEventName
           },
           {
               "locale": "en-GB",
               "providerName": mediaEventProvider,
               "contentName": mediaEventName
           }
       ],
       "relevantAudience": {
           "type": "Multicast",
           "payload": {}
       }
   };
`
Any help to troubleshoot this issue would be helpful.
Thanks,
Srinivas K

**Comment by franklin-lobb** [comment]
Did you sort this out? Can you share how you fixed it?

**Comment by srinivas-kandula** [comment]
Got it working by implementing AlexaSkillEvent.ProactiveSubscriptionChanged handler.

**Comment by yogeshprasad** [comment]
deploy the skill using this template:
https://github.com/dabblelab/alexa-proactive-events-skill-template
