### ISSUE TITLE
Link to Situational Design videos showing Adobe XD from README

### ISSUE THREAD

**Issue by germanviscuso** [alexa/alexa-cookbook#178]
**Please describe what you are looking for:**
Link to situational design videos showing how to work with adobe xd (for example Alexa Live sessions) from README of https://github.com/alexa/alexa-cookbook/tree/master/tools/situational-design
Eg: https://www.youtube.com/watch?v=pyV4dX2HYxE

**Link you used**
https://github.com/alexa/alexa-cookbook/tree/master/tools/situational-design

**Comment by LetMyPeopleCode** [comment]
Auto-closing issues over a year old

**Comment by LetMyPeopleCode** [comment]
Auto-closing issues over a year old
