### ISSUE TITLE
Notification not received

### ISSUE THREAD

**Issue by ravikarthi** [alexa/alexa-cookbook#188]
Hello, 
I'm working on proactive events, While running an order.js it returns 200. but, the notification not received to echo device.

Kindly help me!

**Comment by ravikarthi** [comment]
> Does the device have 'do not disturb' turned on?

No, it's turned Off.

**Comment by ravikarthi** [comment]
In my cloudformation, askLambdaFunctionAlexaTriggerPermission status is "CREATE_IN_PROGRESS".  
Is this the reason for not receiving the notification?

**Comment by ravikarthi** [comment]
Another issue is if I use Unicast in the relevant audience it returns me 403 (User may not be subscribed to this event).
Need some clarity on this. Pls, guide me.
Thanks in advance

**Comment by franklin-lobb** [comment]
Sounds like you might need to re-enable the notifications.

> Enable the skill to receive notifications, as an end user would.
    * Navigate to alexa.amazon.com and log in.
    * Click Skills, then "Your Skills" from the top right.
    * Within the skill list panel, click on "Dev Skills" and then click on your new skill called "Ping Me".
    * Click the Settings button, then click "Manage Permissions".
    * Toggle on the Alexa Notifications option and click Save Permissions.
    You can also perform these steps from the Alexa app on your phone.

I believe multicast returns 200 even if there are zero customers who have enabled notifications (so no one would receive it).

**Comment by ravikarthi** [comment]
Hello Franklin, 
Thank you for your response. I have re-enabled the notification in the Alexa app, but still, I did not get notification.

**Comment by franklin-lobb** [comment]
Strange.  I didn't write the code, but I did try it out and it worked for me.  Couple of other things to check:
* the skill.json has the right event(s) listed as being published (there isn't a mismatch of sending a score report when the skill is configured to send order notifications)
* the device locale matches one of the locales included in the message
* the customer id (userId) is correct - it normally will change each time you disable/re-enable the skill.

**Comment by ravikarthi** [comment]
Hi, Franklin,
I have checked, everything looks Ok. But the issue still resides. I don't know what I have missed.
any other permissions need to enable in AWS platform?

Another issue is, If I send the notification with "Multicast" it returns 202, but it does not work for delivery type "Unicast" (returns 403 - No enablement for clientId).

**Comment by franklin-lobb** [comment]
No, nothing on the AWS side special for this.  If you're getting the 202, its seems like it is a successful call. Since you confirmed the permissions were granted, it sounds a lot like when I crossed my scripts and sent the wrong type of message for what was configured in the skill.json.  You might try cloning the skill into a new directory just to check what's configured. (you'd have to do it this way since it's not visible in the developer console.)

You might also confirm the client id / client secret you are using to obtain the access token is the correct one for your skill.  That is visible on the Permissions page for the skill in the developer console.

**Comment by love2dishtech** [comment]
> Hi, Franklin,
> I have checked, everything looks Ok. But the issue still resides. I don't know what I have missed.
> any other permissions need to enable in AWS platform?
> 
> Another issue is, If I send the notification with "Multicast" it returns 202, but it does not work for delivery type "Unicast" (returns 403 - No enablement for clientId).

Same issue as above. Tried everything suggested here and same behaviour as described. Any solution found?

**Comment by tamerbak** [comment]
Same problem here, Multicast call returns, but when I turn it to Unicast it returns the same problem : "No enablement for clientId"...

**Comment by love2dishtech** [comment]
Yeah, I  couldn't find any solution. But, I did setup a new skill altogether again and this time in the US store as compared to India, and it worked. It could potentially be a regional failure or an issue with the 1st skill.
