### ISSUE TITLE
Encoding problem related to Content-Length in nodejs local-debugger.js response

### ISSUE THREAD

**Issue by pablopen** [alexa/alexa-cookbook#205]
**Describe the bug**
When using characters like the spanish accent mark, the response sent by local-debugger with socket.write doesn't match the number of bytes in Content-Length, and that causes that the json response sent in the body is "truncated" in the response and therefore malformed.

**To Reproduce**
I was using this guide to set up a local debugging/development variable:
https://developer.amazon.com/blogs/alexa/post/77c8f0b9-e9ee-48a9-813f-86cf7bf86747/setup-your-local-environment-for-debugging-an-alexa-skill
which points to a script hosted in this repo
1. go to file alexa-cookbook/tools/LocalDebugger/nodejs/local-debugger.js
2. overwrite response before stringify in line 58 with:
`
            response = {
                "version": "1.0",
                "response": {
                  "outputSpeech": {
                    "type": "SSML",
                    "ssml": "<speak><lang xml:lang=\"es-ES\">La palabra lección tiene tilde. </lang><lang xml:lang=\"en-US\">Translation: the word lesson has accent mark</lang></speak>"
                  },
                  "reprompt": {
                    "outputSpeech": {
                      "type": "SSML",
                      "ssml": "<speak>this is a reprompt</speak>"
                    }
                  },
                  "shouldEndSession": false,
                  "type": "_DEFAULT_RESPONSE"
                },
                "sessionAttributes": {},
                "userAgent": "ask-node/2.7.0 Node/v10.17.0"
              };
`
3. launch an alexa skill pointing to the local endpoint to debug
4. Alexa says it is an "INVALID_RESPONSE"

**Expected behavior**
The response should be valid.

**Environment (please complete the following information):**
node.js v10.17.0. But I think any node would work ( or fail)

**Solution**
I've been able to fix the 1 character 1 byte error with this:
`Buffer.byteLength(response, 'utf8')`
Instead of:
`response.length`
in the Content-Length of line 60.

Do you want me to create a pull request with the change?

**Comment by sattpat** [comment]
Sorry about the late @pablopen . Could you please submit a PR for the bug? Thanks in advance

**Comment by ivanizag** [comment]
I had the same problem. Fixed with the solution proposed.
