### ISSUE TITLE
Example of using both Device Address and Progressive Response API in a single intent in Python

### ISSUE THREAD

**Issue by Aditya050** [alexa/alexa-cookbook#213]
I encountered an issue while using both Device Address API and Progressive Response API in a single intent. The Progressive Response output was OK but the speech that was to be spoken was not spoken. It said that there was an issue with the requested skill's response. 
The CloudWatch Logs did not show any errors too. Please look into this issue

**Comment by Aditya050** [comment]
> I encountered an issue while using both Device Address API and Progressive Response API in a single intent. The Progressive Response output was OK but the speech that was to be spoken was not spoken. It said that there was an issue with the requested skill's response.
> The CloudWatch Logs did not show any errors too. Please look into this issue

**Comment by Aditya050** [comment]
Got a solution for this:
If you are using time.sleep() function then please comment it or change the parameter value in time.sleep() to less than 1. Due to time.sleep() the task got timed out automatically

Still, it would be good if an official documentation for Python is provided for developers

**Comment by YiddishNinja** [comment]
Thanks for the update. Will note your request for an official set of Python docs.
