### ISSUE TITLE
Alexa Skill working on Development but is not working in Alexa app

### ISSUE THREAD

**Issue by abhishek11097** [alexa/alexa-cookbook#221]
I followed each step of the tutorial on proactive events API and created the skill ping me but the skill is not working in alexa app. I am trying the skill using beta testing.

**Comment by abhishek11097** [comment]
Solved it changing the locale

**Comment by SanciuSargas** [comment]
Same here.

**Comment by YiddishNinja** [comment]
Thanks for the reports. Investigating. If you figure it out on your own, please post what you discover.

**Comment by abhishek11097** [comment]
Hi I was able to solve the issue. The skill was made on locale en-US while my Alexa device was in en-IN. Changing the locale of the skill in manifest file solved the issue

**Comment by LetMyPeopleCode** [comment]
Thanks for the upsate. Closing.
