### ISSUE TITLE
Feature demos should be upgraded to ask-cli v2

### ISSUE THREAD

**Issue by tk3369** [alexa/alexa-cookbook#226]
**Is your feature request related to a problem? Please describe.**
The current demos only work with ask-cli v1.

**Describe the solution you'd like**
Upgrade demos so that they are compatible with ask-cli v2.

**Describe alternatives you've considered**
I have to manually convert the ones that I want to play with. 

**Additional context**

**Comment by YiddishNinja** [comment]
Migration performed
