### ISSUE TITLE
AWS Alexa SKill - AWS lambda API error

### ISSUE THREAD

**Issue by ghost** [alexa/alexa-cookbook#23]
Deployed AWS alexa module using AWS lambda deploy.

my zip file contains. package.json package-lock.json node_modules index.js

When i tested my aws lambda function, it failed with Error below. I am using amazon alexa API.

function code call to voice output is:  this.emit('some text');

2017-08-14T06:39:47.468Z 5af7ac74-80bb-11e7-9b7e-5b3b7c9fd513 TypeError: Cannot read property 'emit' of undefined at /var/task/index.js:62:31

**Comment by robm26** [comment]
Hi,
Are you testing it, not with the default test "Hello World", but with the
"Alexa Start Session" event?

**Comment by franklin-lobb** [comment]
closing due to age
