### ISSUE TITLE
Should deploy using supported Node.js version

### ISSUE THREAD

**Issue by idkpmiller** [alexa/alexa-cookbook#232]
Followed the readm instructions for deploying and when I get to ask deploy step this error occurs.

```
$ ask deploy
-------------------- Create Skill Project --------------------
Profile for the deployment: [default]
Skill Id: amzn1.ask.skill.1540987c-ebb8-48f6-91bc-3307c40bd144
Skill deployment finished.
Model deployment finished.
**Create Lambda error.
InvalidParameterValueException: The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions.**
```

Please update to resolve.

**Comment by YiddishNinja** [comment]
We just updated 33 samples to work with ASK CLI v2 which has also upgraded some of them from 8.x to 10.x for the Node version. You will need to upgrade to the v2 CLI as the package structure has changed. As you didn't specify which sample you were trying to deploy, I can't comment specifically, but this should solve your problem.
