### ISSUE TITLE
skill-demo-reminders-api-banana-stand uses deprecated context.System.user.permissions

### ISSUE THREAD

**Issue by rmtuckerphx** [alexa/alexa-cookbook#233]
The [Alexa Developer Forum](https://forums.developer.amazon.com/spaces/23/Alexa+Skills+Kit.html) would be the best source for general help.

[User Voice](https://alexa.uservoice.com) is the best place to submit Alexa Skills Kit feature requests.

**Is your feature request related to a problem? Please describe.**
I am trying to understand the correct pattern to follow when implementing the reminders API and voice permissions. The example uses a deprecated section of the request.

**Describe the solution you'd like**
The sample needs to be updated to no longer use `context.System.user.permissions` and show the correct pattern to follow.

**Describe alternatives you've considered**
Need a comprehensive example that show Reminders, voice permission for reminders, and when (if at all) you need to send a card to the Alexa App for reminder permissions.

**Additional context**
See line 35 & 42 for the deprecated code: https://github.com/alexa/alexa-cookbook/blob/ae88ca5d1970af32cfb582720d378a6db9823f8d/feature-demos/reminders-api/skill-demo-reminders-api-banana-stand/lambda/index.js

This document shows that the permissions section is deprecated:
https://developer.amazon.com/en-US/docs/alexa/custom-skills/request-and-response-json-reference.html#session-object

**Comment by LetMyPeopleCode** [comment]
Hi Mark,

This has now been addressed.
