### ISSUE TITLE
Missing link to Model in readme file

### ISSUE THREAD

**Issue by jallwork** [alexa/alexa-cookbook#236]
The link to the Model on the read me file doesn't work.

Clicking on 'Model' takes you to:
https://github.com/alexa/alexa-cookbook/blob/master/feature-demos/skill-demo-display-directive/models/en-US.json

which doesn't exist

**Comment by YiddishNinja** [comment]
Thanks. The migration to ASK CLI V2 moves files but doesn't update links to them. Thanks for the catch.
