### ISSUE TITLE
local-debugger.js attempts to parse a partial json payload from alexa

### ISSUE THREAD

**Issue by j-vasanth** [alexa/alexa-cookbook#250]
**Describe the bug**
The payload that that local-debug.js receives when the data event triggers on the socket is not complete and the debugger fails attempting to parse it. 
Upon further investigation I noticed that the tcp chunk that was received on that instance of data event is not the complete body. I think this is a bug since we are incorrectly handling the http protocol on tcp by assuming that the entire payload is transmitted in the first chunk.

**To Reproduce**
I just followed the documented steps on setting up local debugging and I consistently fail with malformed json failures. I used pagekite instead of ngrok for my reverse proxy. 

**Expected behavior**
I expect the local debugger to correctly handle http post requests.

**Environment (please complete the following information):**
 - OS: macOS
 - Version Mojave 10.14.6

**Additional context**
I was able to fix the issue by migrating local-debugger to use the http library for nodejs (https://nodejs.org/api/http.html). I think this is a more robust way to handle http posts instead of custom http implementation on raw tcp sockets. I am happy to submit a pull request for this, if my solution can be agreed upon.

**Comment by emilioyn** [comment]
Hello, what did you change? Could you, please, share your code? Thank you!

**Comment by j-vasanth** [comment]
Link to the [modified local-debugger](https://gist.github.com/j-vasanth/7c75e6479440b164179031a4b9ffc60a). I basically swapped to using nodejs's http server instead of implementing http on raw sockets like what the current debugger does. The code is exactly the same otherwise.

**Comment by emilioyn** [comment]
Great! Thank you! Yeah, this code seems to be much more robust...

**Comment by j-vasanth** [comment]
> Great! Thank you! Yeah, this code seems to be much more robust...

Yeah, I think I should just go ahead and submit a pull request, will help out a lot of folks.
