### ISSUE TITLE
Incorrect link to internal docs

### ISSUE THREAD

**Issue by chrismessina** [alexa/alexa-cookbook#255]
**Describe the bug**
On this page:
https://github.com/alexa/alexa-cookbook/tree/master/feature-demos/alexa-conversations/intro-to-alexa-conversations

Under the heading "Skill Functionality"

There is a link to:
https://developer.integ.amazon.com/en-US/docs/alexa/conversations/about-alexa-conversations.html

It should link to:
https://developer.amazon.com/en-US/docs/alexa/conversations/about-alexa-conversations.html

**Comment by ajot** [comment]
Fixed with 312143cb5f524e71a10e784402a6778bfa6ff8e8
