### ISSUE TITLE
smapi-sdk-node-demo smapi instructions are completely incorrect for ask cli v2.14.0

### ISSUE THREAD

**Issue by talkingnews** [alexa/alexa-cookbook#263]
https://github.com/alexa/alexa-cookbook/tree/master/feature-demos/smapi-sdk-node-demo

The instructions are completely incorrect and misleading. To save anyone else having to waste over 20 hours on this:

Go to: 
https://developer.amazon.com/loginwithamazon/console/site/lwa/overview.html - create new token

Go to "allowed return URL" on the "web settings" tab of that new token, and you MUST add:

```
http://127.0.0.1:9090/cb
https://s3.amazonaws.com/ask-cli/response_parser.html
https://ask-cli-static-content.s3-us-west-2.amazonaws.com/html/ask-cli-no-browser.html 
```

That third one is essential, and does not appear to be mentioned anywhere. I only figured it out from the URL which is shown from the generate-lwa-tokens command.

Then you can run:

`ask util generate-lwa-tokens --client-id <client id> --client-confirmation <client-secret> --no-browser --scopes alexa::ask:skills:readwrite alexa::ask:models:readwrite alexa::ask:skills:test`

eg

`ask util generate-lwa-tokens --client-id amzn1.application-oa2-client.02xxxx --client-confirmation 38x --no-browser --scopes alexa::ask:skills:readwrite alexa::ask:models:readwrite alexa::ask:skills:test`

Confusingly, "client_confirmation" is actually "client_secret"

## Possible reason for problem:
When you do `ask util generate-lwa-tokens --no-browser` it takes you to a link which includes client_id=amzn1.application-oa2-client.aad322b5faab44b980c8f87f94fbac56

`https://www.amazon.com/ap/oa?response_type=code&client_id=amzn1.application-oa2-client.aad322b5faab44b980c8f87f94fbac56`

I don't know who amzn1.application-oa2-client.aad322b5faab44b980c8f87f94fbac56 belongs to, but the returned tokens are clearly for someone else's account, which also appears in example code here: https://developer.amazon.com/en-US/docs/alexa/smapi/audit-logs-api.html

In addition, ask util generate-lwa-tokens  does not appear to work *at all* via a browser, and the command simply serves an empty page and then immediately exits.

Also, unless you specify those scopes, which the document says are optional, again it will not work.

Finally, https://developer.amazon.com/loginwithamazon/console/site/lwa/overview.html and 
https://developer.amazon.com/settings/console/securityprofile/overview.html appear to be different pages showing the same info.

These are all yet more problems of ask cli v2 and its accompanying documentation, which appears still be untested or checked, and is providing frustration and huge amounts of time-waste to many developers.

**Comment by talkingnews** [comment]
I am still unable to find the correct scope for use with smapi node client.

For example, this works:
`ask smapi get-interaction-model --skill-id amzn1.ask.skill.80fXXXXX --stage development --locale en-GB`

But this does not, even if I use the exact same credentials as the ask CLI, or I get new ones.

`smapiClient.callGetInteractionModelV1('amzn1.ask.skill.80fXXXXX', 'development', 'en-GB')`

I just get

`response: { message: 'User has not consented to this operation.' }`

I can do everthing else with the node smapi client, but not interactionmodel functions

`ask util generate-lwa-tokens --client-id amzn1.application-oa2-client.02dXXXX --client-confirmation 382XXXXX --no-browser --scopes alexa::ask:skills:readwrite alexa::ask:models:readwrite alexa::ask:skills:test alexa::ask:catalogs:read alexa::ask:catalogs:readwrite alexa::ask:subscriptions alexa::ask:skills:debug`

I have tried different scopes, including with and without the skills:debug

I have also added more details to another user's post with a similar problem
https://forums.developer.amazon.com/questions/89552/login-with-amazon-says-user-has-not-consented-but.html

UPDATE: I have looked at the headers sent via the two methods, and they seem identical, except that that ask-cli which works has:


```
  {
            "key": "x-amz-date",
            "value": "Tue, 11 Aug 2020 13:35:09 GMT"
        },
        {
            "key": "etag",
            "value": "caa7919c30397eXXXXXbafbac92dc"
        },
        {
            "key": "vary",
            "value": "Content-Type,Accept-Encoding,X-Amzn-CDN-Cache,X-Amzn-AX-Treatment,User-Agent"
        },
        {
            "key": "x-cache",
            "value": "Miss from cloudfront"
        },
```

And the smapi node client which says ""User has not consented to this operation." has this:

```
  {
            "key": "x-amz-date",
            "value": "Tue, 11 Aug 2020 13:42:34 GMT"
        },
        {
            "key": "www-authenticate",
            "value": "Bearer realm=\"Login with Amazon\""
        },
        {
            "key": "vary",
            "value": "Content-Type,Accept-Encoding,X-Amzn-CDN-Cache,X-Amzn-AX-Treatment,User-Agent"
        },
        {
            "key": "x-cache",
            "value": "Error from cloudfront"
        },
```

**Comment by LetMyPeopleCode** [comment]
Looks like you're leaving this in multiple repositories. The engineering team has been engaging with you over in https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/issues/638.  We're closing the issue here.

**Comment by talkingnews** [comment]
Hi @LetMyPeopleCode - I was posting it in the relevant repositories where people would be having problems. I can see that this is a widespread issue causing problems to lots of people, and until the docs are fixed, I thought I could save someone else spending days trying to find the solution.

If you're going to close it, at least ensure the cookbook has instructions that will work - for example, you cannot use the default account, and even the instructions at #638 are not quite correct, because `alexa::ask:skills:debug` makes it fail until removed.

**Comment by LetMyPeopleCode** [comment]
We will link to the eventual solution as appropriate.
