### ISSUE TITLE
Typo in package.json for Alexa conversation

### ISSUE THREAD

**Issue by jlecomte-IED** [alexa/alexa-cookbook#264]
**Describe the bug**
typo in alexa-cookbook/feature-demos/alexa-conversations/pizza-reference-skill/package.json

**To Reproduce**
  "keywords": [
    "pizza",
    "convefsations"
  ],

**Expected behavior**
  "keywords": [
    "pizza",
    "conversations"
  ],

**Comment by LetMyPeopleCode** [comment]
Resolved
