### ISSUE TITLE
Timer permission not working for user

### ISSUE THREAD

**Issue by danieldhz** [alexa/alexa-cookbook#270]
Hi All!
I have built a timer api for my skill. But when I go to the app & click grants permission, the permission no longer gets granted. Is this an internal alexa error? What shall i do?
https://amazonalexa.slack.com/files/U016RVBC2DP/F019W7LD53Q/alexa.mp4

**Comment by SleepyDeveloper** [comment]
Please ask this question on the developer forum. https://forums.developer.amazon.com/spaces/23/Alexa+Skills+Kit.html
