### ISSUE TITLE
400 response when running the script media.js

### ISSUE THREAD

**Issue by chandlerjwang** [alexa/alexa-cookbook#272]
https://github.com/alexa/alexa-cookbook/blob/90de4b0ccbf508c0e6d1ad16535e179004db2e10/feature-demos/skill-demo-proactive-events/media.js#L51

the current media.js won't execute successfully and return 400.

The issue is in the referenced line in media.js, expiryTime is less than timestamp.

the correct code should be below:

```
expiryTime.setMinutes(expiryTime.getMinutes() + 24); // The maximum allowed expiryTime value is 24 hours, and the minimum is 5 minutes.
```

Tech Reference: https://developer.amazon.com/en-US/docs/alexa/smapi/proactive-events-api.html#proactive-events-api-parameters

![image](https://user-images.githubusercontent.com/21047496/93540217-d8773600-f907-11ea-9b63-2bd0eb7b5f84.png)

**Comment by LetMyPeopleCode** [comment]
Thanks Chandler.
