### ISSUE TITLE
Basic Deployment Instructions Missing for ask cli v2

### ISSUE THREAD

**Issue by error454** [alexa/alexa-cookbook#273]
**Please describe what you are looking for:**
This repo contains a mix of projects using ask cli project structure 1.1 and 2.

skill-demo-tasks - v2
skill-demo-timers - v2
everything else - v1.1

This repo does not contain any instructions on how to upgrade or deploy projects for those using `ask` cli v2. The rest of the alexa documentation ecosystem is pushing v2 at this point and it would be very helpful to mention that in the repo docs.

To save 4-6 hours for the next person that might be getting an error about the `ask-resources.json` file not existing when they go to deploy:

Many of the projects in this repo use the old `ask` cli 1.1 project structure. This can be recognized by the presence of an `.ask` folder in the root of the example folder. Whereas example projects with the file `ask-resources.json` in the root folder are on the 2.X project structure [according to this migration guide](https://developer.amazon.com/en-US/docs/alexa/smapi/ask-cli-v1-to-v2-migration-guide.html).

To be able to deploy an example using the latest (2.0) version of the `ask` cli you first need to upgrade the example to the 2.0 project structure. To do this run `ask util upgrade-project` in the root of the example. For example the `skill-demo-list-access` sample:
`zach@computer:/projects/alexa-cookbook/feature-demos/list-api/skill-demo-list-access$ ask util upgrade-project`

Once the project structure is upgraded, you can run `ask deploy` as normal.

**Comment by error454** [comment]
Doing a survey of the example projects I see in this repo gives me the following:

|Example|Project Structure|
|:--|:--|
|apl/skill-demo-apl-pager|1.1
|apl/skill-demo-apl-video|1.1
|apl/skill-demo-aplt-text|custom
|apl/skill-demo-interactive-apl-button|1.1
|apl/skill-demo-lazy-load-lists|custom
|aws/aws-demo-amazon-sqs|1.1
|dynamic-entities/skill-demo-dynamic-entities|1.1
|dynamic-entities/skill-demo-dynamic-heroes|1.1
|list-api/skill-demo-create-get-custom-list|???
|list-api/skill-demo-list-access|1.1
|list-api/skill-demo-list-events|1.1
|reminders-api/Skill-demo-Medicine-reminder-python|???
|reminders-api/skill-demo-recurring-reminders|custom
|reminders-api/skill-demo-reminders|1.1
|reminders-api/skill-demo-reminders-api-banana-stand|???
|skill-connections/provider-demo|1.1
|skill-connections/requester-demo|1.1
|skill-demo-amazon-pay|1.1
|skill-demo-customer-profile|1.1
|skill-demo-delete-persistent-attributes|1.1
|skill-demo-device-location|1.1
|skill-demo-device-settings|1.1
|skill-demo-dialog-delegate|1.1
|skill-demo-display-directive|1.1
|skill-demo-dynamic-location|1.1
|skill-demo-entity-resolution|1.1
|skill-demo-intent-chaining-auto-delegate|1.1
|skill-demo-person-profile|1.1
|skill-demo-personalization|1.1
|skill-demo-proactive-events|1.1
|skill-demo-progressive-response|1.1
|skill-demo-s3-select|1.1
|skill-demo-shared-slots|1.1
|skill-demo-tasks|2.0
|skill-demo-timers|2.0
|skill-demo-videoapp-directive|1.1

The examples marked with ??? above indicate in their readme files that they are `structured to make it simple to deploy with the ask cli` but then go on to provide directions unrelated to using the cli. They do not contain the 1.1 or 2.0 project structure so it is not clear how to deploy them using ask. Can someone provide instructions?

**Comment by LetMyPeopleCode** [comment]
There is a V2 branch of the repo where V2 converted versions were placed. When telemetry shows developer adoption of 2.0 has reached a certain level, the main and V2 branches will be swapped. We'll look at making this clearer.

**Comment by error454** [comment]
A simple mention in the readme would have sufficed for me.
