### ISSUE TITLE
"One-page design sheets" Amazon Drive link is broken

### ISSUE THREAD

**Issue by codegamc** [alexa/alexa-cookbook#280]
**Please describe what you are looking for:**
On [this page](https://github.com/alexa/alexa-cookbook/tree/master/tools), there is a section at the top for _"One-page design sheets can be printed and used to sketch out ideas for a conversation with Alexa."_

These links direct to an empty folder in Amazon Drive

**Link you used**
[Link One](https://www.amazon.com/clouddrive/share/5WMoGXcKHSWWSoRiC3VNFmBnEveQBdPnLZq711Iu3d?_encoding=UTF8&mgh=1&ref_=cd_ph_share_link_copy)
[Link Two](https://www.amazon.com/clouddrive/share/PLKDyDip6Jv1HK450NTTGzJZJB4QjDyYxTMlQgmWDCQ?_encoding=UTF8&mgh=1&ref_=cd_ph_share_link_copy)

**Source of the link**
See description

**Additional context**
None

**Comment by LetMyPeopleCode** [comment]
Thanks. We've updated the section.
