### ISSUE TITLE
Upgrade ProactiveEvents API Example to v2 ask-cli

### ISSUE THREAD

**Issue by codegamc** [alexa/alexa-cookbook#281]
**Describe the bug**
When trying to run the PE API Example, I am faced with an error when running `ask deploy` from command line. Following the warning message is successful, and results in a functional demo

**To Reproduce**
1. Go to [this demo](https://github.com/alexa/alexa-cookbook/tree/master/feature-demos/skill-demo-proactive-events)
2. Complete steps through [this header](https://github.com/alexa/alexa-cookbook/tree/master/feature-demos/skill-demo-proactive-events#skill-setup-steps)
3. Then continue with steps until 

> "Run the command ask deploy to create the skill."

5. Attempt that step
6. This is the output:

```
[Warn]: File ~/alexa-cookbook/feature-demos/skill-demo-proactive-events/skill/ask-resources.json not exists. If this is a skill project managed by v1 ask-cli, please run 'ask util upgrade-project' then try the command again
````

**Expected behavior**
An example from Alexa would be upgraded to the latest version of the CLI, or have a warning stating that it uses an outdated version (even if compatible with simple update)

**Environment (please complete the following information):**
 - OS: MacOS
 - Version 10.15.6

**Additional context**
The ask CLI used was the latest available as of Dec 19, 2020. CLI installed with `npm install -g ask-cli` on 12-19

**Comment by jallwork** [comment]
I have the same problem.  Windows 10.
Follow the demo
Running 'ask deploy' under Visual Studio Code, the warning message is:
[Warn]: File C:\Users\...\alexa-cookbook\feature-demos\skill-demo-proactive-events\ask-resources.json not exists.

Tree:
   ├───skill-demo-proactive-events
│   │   │   LICENSE
│   │   │   media.js
│   │   │   order.js
│   │   │   README.md
│   │   │
│   │   └───skill
│   │       │   skill.json
│   │       │
│   │       ├───.ask
│   │       │       config
│   │       │
│   │       ├───lambda
│   │       │   └───custom
│   │       │           constants.js
│   │       │           helpers.js
│   │       │           index.js
│   │       │           interceptors.js
│   │       │           package.json
│   │       │           schedule.txt
│   │       │
│   │       ├───models
│   │       │       en-US.json
│   │       │
│   │       └───sam
│   │               deploy.sh
│   │               deploy.unix.sh
│   │               pingme.yaml

It doesn't exist.

**Comment by LetMyPeopleCode** [comment]
Please try the V2 branch of the skill. V1 samples are not yet deprecated. Apologies for any confusion.
