### ISSUE TITLE
Reminders API 401 Unauthorized

### ISSUE THREAD

**Issue by ahmednkhan24** [alexa/alexa-cookbook#282]
I am following [this cookbook recipe](https://github.com/alexa/alexa-cookbook/blob/master/feature-demos/reminders-api/skill-demo-reminders/lambda/custom/index.js).

Before I even try to create a reminder, I first want to simply verify if I am able to even retrieve the list of reminders from the device. 

I have verified that my skill does have the correct permission toggled for "reminders."

I verified that a consent token is being retrieved, but I am still failing to retrieve a count of reminders for my device with a http 401 code for unauthorized. 

My updated code can be [found here.](https://github.com/ahmednkhan24/alexa-athan/blob/main/index.js#L58)

Error in the logs: 

> UserAuthenticationException. Request is not authorized/authenticated e.g. If customer does not have permission to create a reminder.

 - Skill is on the developer console
 - Lambda is on AWS.

**Comment by LetMyPeopleCode** [comment]
"The apiAccessToken is included on all requests to your skill, regardless of whether the user granted your skill the permissions needed to fulfill the request." The most common cause for this is that you didn't grant the permissions.

Turning it on in the permissions page of your developer console doesn't get you permission from the owner of the device. In the simulator, the owner is an account with the same email/phone as your developer account. 

Do you have an Alexa app running on your phone that is tied to the same email/phone your developer account is tied to? Did you approve the request via the card sent to that app?
