### ISSUE TITLE
Can't find where do submit issues for Alexa documentation

### ISSUE THREAD

**Issue by matijagrcic** [alexa/alexa-cookbook#291]
**Please describe what you are looking for:**
Can't find where do submit issues for Alexa documentation

**Link you used**
https://developer.amazon.com/en-US/docs/alexa/custom-skills/host-a-custom-skill-as-an-aws-lambda-function.html#configuring-the-alexa-skills-kit-trigger

**Broken markdown**
```
When using skill ID verification, you do not need to include code to [verify that the request is intended for your service][handling_req#request-verify]. Requests from unverified skills do not invoke your function.
```

```
You may have older Lambda functions that have skill ID verification setup as part of the function's code as described in [Verifying that the Request is Intended for Your Service][handling_req#request-verify]. 
```

The above are two examples of broken markdown and thus the documentation on the official docs. I've tried searching the alexa org but couldn't find where can i submit an PR to correct this.

**Comment by LetMyPeopleCode** [comment]
Hi, there is a feedback tab on the side of the documentation pages where you can submit feedback. The Alexa docs are not maintained as a public repo and there is no PR process.

**Comment by matijagrcic** [comment]
There's no **Feedback** on the Alexa Docs, only on  the AWS docs.

**AWS Docs**
![image](https://user-images.githubusercontent.com/3612395/111348789-d4429000-8680-11eb-86c1-5277a8e0219c.png)

**Alexa Docs**
![image](https://user-images.githubusercontent.com/3612395/111348826-dd336180-8680-11eb-8ce9-cc0b883116f0.png)

**Comment by LetMyPeopleCode** [comment]
Bottom right corner.
![image](https://user-images.githubusercontent.com/10713246/111352706-b6a20600-8641-11eb-971c-d82a7c3db57d.png)

**Comment by matijagrcic** [comment]
Ah ok, I don't see this, seems blocked by PiHole.
