### ISSUE TITLE
Repo not linked properly > 404

### ISSUE THREAD

**Issue by julesmoretti** [alexa/alexa-cookbook#34]
Under section 8. of https://github.com/alexa/alexa-cookbook/blob/master/handling-responses/dialog-directive-delegate/step-by-step/2-lambda-function.md

Both links "provided code" and "GitHub" returns 404.

Could the whole step 8.2.1 to 8.2.4 be prebuilt? As this adds unnecessary complexity for this tutorial.

Thank you.

**Comment by SleepyDeveloper** [comment]
The "provided code" and "GitHub" links also appear to be redundant. 

The indents in the file are also making it into a code block. I'll fix this.

I do like the idea of prebuilt lambda functions that can be used to test out the tutorials. 
I'll have to look into that.

**Comment by SleepyDeveloper** [comment]
This has been fixed.
