### ISSUE TITLE
isSimulator() function in Display Directive example

### ISSUE THREAD

**Issue by xiehan** [alexa/alexa-cookbook#38]
The [display-directive example](https://github.com/alexa/alexa-cookbook/blob/master/display-directive/bodyTemplate/) contains the following function:

```
function isSimulator() {
  var isSimulator = !this.event.context; //simulator doesn't send context
  return isSimulator;
}
```

However, when I go to test my skill in the Service Simulator, if I use the "Text" tab (default), the generated Service Request always contains context:

```json
"context": {
    "AudioPlayer": {
      "playerActivity": "IDLE"
    },
    "System": {
      "application": {
        "applicationId": "<redacted>"
      },
      "user": {
        "userId": "<redacted>"
      },
      "device": {
        "supportedInterfaces": {}
      }
    }
  },
```

If I use the "JSON" tab and either try to omit the context or add `"Display": true` to `supportedInterfaces`, I get an error saying my request is invalid.

As a result, I don't know how to test my Echo Show templates, since I already have non-Show-user beta testers on my app, so I have to check that the display directive is supported before rendering the template. All I'm getting in the Service Simulator are the default Echo Show templates generated from the Alexa app cards; I can't for the life of me figure out how to have it render the fancier templates.

**Comment by franklin-lobb** [comment]
the simulator now renders the templates so special casing is no longer required.  Please reopen if you have any further questions.
