### ISSUE TITLE
SayArray function skipping array entries

### ISSUE THREAD

**Issue by simonreid123** [alexa/alexa-cookbook#47]
The SayArray function will say the first entry and the last two, i.e.
sayArray(['one', 'two', 'three', 'four', 'five'], 'and')
will return
'one, four and five'

**Comment by SleepyDeveloper** [comment]
Nice catch!! Thanks for bringing this to my attention!

I'll update this. I've updated the original function to use ES6.

**Comment by SleepyDeveloper** [comment]
This has been updated. Converting to ES6 has made the function a lot easier to read and a the logic has also been simplified. 

https://github.com/alexa/alexa-cookbook/blob/59dd5fb75ffe1ce28bfb5f614672a8b41d1ca665/handling-responses/say-array/src/index.js#L47
