### ISSUE TITLE
Full user utterances?

### ISSUE THREAD

**Issue by shivamgupta211** [alexa/alexa-cookbook#48]
How can i get the complete user utterance ?

**Comment by JennJin** [comment]
Hi, Alexa uses an Interaction Model comprising of Intents and Utterances to pass through the key items a Skill would need to handle the User's Intent. It reduces the onus on the skill to extract what the user intends and improves the recognition accuracy with 'training data'.
If you need the full utterance here's a blog post which provides a possible solution: [Why a Custom Slot is the Literal Solution
](https://developer.amazon.com/blogs/post/Tx3IHSFQSUF3RQP/why-a-custom-slot-is-the-literal-solution)

I would also search the [Alexa Dev Forum](https://forums.developer.amazon.com/spaces/23/Alexa+Skills+Kit.html) for what other developers have done.
