### ISSUE TITLE
Error in steps to work with DynamoDB

### ISSUE THREAD

**Issue by souvikbasu** [alexa/alexa-cookbook#49]
Go to url: https://github.com/alexa/alexa-cookbook/tree/master/aws/Amazon-DynamoDB/read#grant-dynamodb-permissions-via-iam
Point 4 mentions:
For a quick demo, filter on "DynamoDB" and attach the AmazonDynamoDBReadOnlyAccess policy.

This didn't work for me.
I guess it should be: AmazonDynamoDBFullAccess

**Comment by Liamdelee** [comment]
if it is for read onlly this should work if you enabled this correctly.
I myself howerver like it more fine grained so i am just using this statement for a query onlly
`{
 "Version": "2012-10-17",
 "Statement": [
  {
   "Effect": "Allow",
   "Action": [
    "dynamodb:Query"
   ],
   "Resource": [
    "arn:aws:dynamodb:eu-west-1:YOUR_NUMBERS_HERE:table/YOUR_TABLE_NAME_HERE"
   ],
   "Condition": {
    "ForAllValues:StringEquals": {
     "dynamodb:LeadingKeys": [
      "${graph.facebook.com:id}"
     ]
    }
   }
  }
 ]
}`

**Comment by franklin-lobb** [comment]
closing due to age
