### ISSUE TITLE
testing/TestFlow: Unexpected exception 'TypeError: Cannot read property 'value' of undefined'

### ISSUE THREAD

**Issue by trod-123** [alexa/alexa-cookbook#5]
Error comes up when an intent has multiple slots, and user only provides input for only some but not all of the slots.

Example:
BaseInput BASE_SPOKEN= baseNum= PRE_BASE_SPOKEN= preBase=2 POST_BASE_SPOKEN= postBase=

Is there a way to indicate "undefined" or "null" values in the dialog sequence file?

Many thanks,
TR

**Comment by franklin-lobb** [comment]
You can specify a 'null' slot by simply omitting the slot value, like this:

`MyColorSetIntent color=`
