### ISSUE TITLE
Simplified install instructions for TestFlow

### ISSUE THREAD

**Issue by talkingnews** [alexa/alexa-cookbook#51]
If you just want a quick 'n' dirty test of TestFlow to check it does what you want/need, then try this (not all steps will be needed):
```
mkdir testing
cd testing
apt install svn
svn checkout https://github.com/alexa/alexa-cookbook/trunk/testing/TestFlow
cd TestFlow/src
npm install
cd ..
node testflow staterequest.txt
```

**Comment by franklin-lobb** [comment]
Thanks for sharing this, however I don't see a good place to include this in the setup steps, so I'm going to just close this issue.  If you see a place for it, feel free to open a pull request.
