### ISSUE TITLE
Displaying bodytemplate6 initial test with just a full screen image

### ISSUE THREAD

**Issue by yosun** [alexa/alexa-cookbook#56]
i can't seem to get it to work. i am testing with the response being just the image URL in the full screen bodytemplate6 by just modifying your code with a different template (also getting rid of most of the fact app stuff) 

The error I get is the response is invalid? Expecting string,number,null,true,false got undefined  

https://gist.github.com/yosun/1be49dad42b1d008e5207492096e612a

**Comment by franklin-lobb** [comment]
for a current sample using the display templates, check out [Berry Bash](https://github.com/alexa/skill-sample-nodejs-berry-bash), or better yet, check out the APL samples here: https://github.com/search?q=topic%3Aalexa-presentation-language+org%3Aalexa-labs&type=Repositories
