### ISSUE TITLE
There are two testflow.js files in the testflow recipe, and one is out of date

### ISSUE THREAD

**Issue by talkingnews** [alexa/alexa-cookbook#59]
This works and looks up to date
https://github.com/alexa/alexa-cookbook/blob/master/testing/TestFlow/testflow.js

This doesn't work and is missing several debugging options
https://github.com/alexa/alexa-cookbook/blob/master/testing/TestFlow/src/testflow.js

Suggest removing the second copy in src as it might confuse someone, especially if they try and run it.

**Comment by SleepyDeveloper** [comment]
Thanks for reporting. The second copy has been removed.
