### ISSUE TITLE
saying working without sdk but inline comments say it does but it does not

### ISSUE THREAD

**Issue by Liamdelee** [alexa/alexa-cookbook#66]
at alexa-cookbook/handling-responses/dialog-directive-delegate/sample-nodejs-plan-my-trip/src/SampleWithoutTheSDK.js you work with a sample without the SDK but inline on line four says:

> * This sample demonstrates a simple skill built with the Amazon Alexa Skills Kit.

just so you people know and can get it updated

**Comment by franklin-lobb** [comment]
the plan my trip demo has been updated, so this comment has been addressed.
