### ISSUE TITLE
Extend HttpsGet sample with audio feedback "calling an API..."

### ISSUE THREAD

**Issue by homtec** [alexa/alexa-cookbook#67]
Hi,

please extend the sample HttpsGet with code telling the user that an API is going to be called and it may take a while. I'm wondering what's the best way to do.

Thank you,
Thomas

**Comment by franklin-lobb** [comment]
the progressive response sample does this: https://github.com/alexa/alexa-cookbook/tree/master/feature-demos/skill-demo-progressive-response
