### ISSUE TITLE
Invalid category: 

### ISSUE THREAD

**Issue by laynr** [alexa/alexa-cookbook#73]
Line 18 in master/labs/HelloWorld/skill.json results in the error shown below when doing "ask deploy"

To fix this change line 18 FROM:
       "category": "TRIVIA",
TO:
       "category": "KNOWLEDGE_AND_TRIVIA",

```
ask deploy
-------------------- Create Skill Project --------------------
Profile for the deployment: [default]
  \  Creating new skill...Call create-skill error.
Error code: 400
{
  "message": "The skill manifest is not valid.",
  "violations": [
    {
      "message": "Invalid category."
    }
  ]
}

```

**Comment by SleepyDeveloper** [comment]
@laynr This has been fixed. Thanks for reporting!
