### ISSUE TITLE
Error parsing the requested content:  alexa/alexa-cookbook/labs/HelloWorld/

### ISSUE THREAD

**Issue by laynr** [alexa/alexa-cookbook#74]
Followed all steps fine but get the error below when doing ask deploy.  Do not know what is causing the error.  The skill  get created in developer.amazon.com, but the lambda function does not get created in console.aws.amazon.com.

ask deploy
-------------------- Create Skill Project --------------------
Profile for the deployment: [default]
Skill Id: amzn1.ask.skill.68b7875d-XXXX-XXXX-XXXX-XXXXXXXXX
Skill deployment finished.
Call update-model error.
Error code: 400
{
  "message": "The request is not valid.",
  "violations": [
    {
      "message": "Error parsing the requested content. Please validate the input"
    }
  ]
}

**Comment by mavnorthwind** [comment]
I got the same error.
Which locale do you use? I got a feeling that alexa cookbook only works for US machines using the US AWS.

**Comment by error404notfound** [comment]
I also have this error.  has there been any resolution or confirmation regarding this?

**Comment by megantosh** [comment]
same here, it happened after failed uploads because of a syntax error in de-DE.json

**Comment by kumarks102** [comment]
IS there any update ? Even i am also struck with this issue.

**Comment by error404notfound** [comment]
HI there. I did a new clone of the repository it only has the us json now? 
and it seems to deploy and function aok.

**Comment by franklin-lobb** [comment]
Sorry for the churn, however this lab was moved to its own repo and the version here should have been removed.  Check out https://github.com/Alexa/skill-sample-nodejs-hello-world/.  If you have any trouble with that, please open up an issue there.

**Comment by franklin-lobb** [comment]
closing due to age
