### ISSUE TITLE
How to use httpsGet code if you want myRequest value to change based on user input

### ISSUE THREAD

**Issue by smach** [alexa/alexa-cookbook#76]
I understand how to make an API call using Node.js. My issue is **how to change the hard-coded myRequest value based on a slot in my Alexa Skill**, since I don't want to use an API in my skill for a single, hard-coded value. Is there code anywhere showing how to return API results based on a slot value that a user speaks?

**Comment by SleepyDeveloper** [comment]
Take a look at [petmatch](https://github.com/alexa/skill-sample-nodejs-petmatch/). It uses entity resolution to map slot values to api key values that are passed to and api call via httpGet.

**Comment by smach** [comment]
Thanks @SleepyDeveloper ! I do think it would be useful to show how to do this in the httpsGet code, though

**Comment by franklin-lobb** [comment]
I think the example you are looking for can be found in this blog post: https://developer.amazon.com/blogs/alexa/post/28368692-a0b9-4579-b129-e6793bef7848/alexa-skill-recipe-update-making-http-requests-to-get-data-from-an-external-api-using-the-ask-software-development-kit-for-node-js-version-2

**Comment by franklin-lobb** [comment]
Sorry, didn't mean to close the issue. :flushed:

**Comment by smach** [comment]
Thanks that looks promising, I'll have to run through the example code this weekend.
