### ISSUE TITLE
plan my trip dialog does not work as shown in video

### ISSUE THREAD

**Issue by emgould** [alexa/alexa-cookbook#77]
I deployed the function to lambda, imported the voi and sucessfully connected them.  However, when you test it the skill does not have the dialogue interaction that is "advertised".  Try it.
  "Open plan my trip"
              Alexa: "Lets plan a trip. Where would you like to go?"
 "I would like to go to Portland"
             Alexa: "The fastest route to Portland is...."

It does not prompt you for were you are leaving from or when you want to go.  As is suggested by both this tutorial and the videos with the interactive beta.

**Comment by celoaiza** [comment]
It does work, but you have to build a zip file including the index, node modules and latest alexa sdk library. Then upload the zip file to lambda. It looks like the latest alexa sdk build is not available as default.

**Comment by franklin-lobb** [comment]
@emgould sounds like the skill is exiting.  that could happen if you don't respond within 8 seconds, or if the skill encounters an error and exits.  I would suggest looking in the logs for an error message which could provide a clue as to what is happening.

Also, plan my trip has been updated to use the latest SDK.  Check it out.
