### ISSUE TITLE
Conditional intent routing only works with LaunchRequest, not NewSession

### ISSUE THREAD

**Issue by talkingnews** [alexa/alexa-cookbook#78]
Anyone having problems with intent routing? 

I'm following this section from the cookbook, using latest Node ASK SDK v1.0.24:

https://github.com/alexa/alexa-cookbook/blob/master/ingredients/using-new-session-to-short-circuit-incoming-intent-and-launch-requests.md

It says:
```
// This will short-cut any incoming intent or launch requests and route them to this handler.
'NewSession': function() {
      if (this.event.request.type === 'IntentRequest') {
          this.emit(this.event.request.intent.name); 
      } 
      this.emit('LaunchRequest');
}
```
> To route to the original intent, we emit the original intent via `this.event.request.name`

Seems fair enough. So I tried it, and it's not working. I've console-logged everything, and it definitely is catching the intent. Here's my code:

```
'NewSession': function () {
			console.log("In newsession function within menu");
			if (this.event.request.type === 'IntentRequest') {
				console.log("got an intentrequest within newsession in menu of " + this.event.request.intent.name);
				console.log(this.attributes.STATE);
				this.emit(this.event.request.intent.name);
			}
			this.handler.state = constants.states.MENU_MODE;
			this.emit('MenuIntent');
		},
```

And here's my log output:

```
got an intentrequest within newsession within menu:  AMAZON.HelpIntent
In menuintent function within menu
```
So it definitely catches it, but doesn't reroute. **But if I change newsession to launchrequest, it works!**
 Where am I going wrong?!

**Comment by franklin-lobb** [comment]
Sounds like you wanted to do some intent chaining or conditional responding based on the request.  You can learn more about the former here: https://developer.amazon.com/blogs/alexa/post/9ffdbddb-948a-4eff-8408-7e210282ed38/intent-chaining-for-alexa-skill, and the latter by leveraging the canHandle conditions described in the latest SDK docs: https://ask-sdk-for-nodejs.readthedocs.io/en/latest/Processing-Request.html
