### ISSUE TITLE
Can't follow the instructions

### ISSUE THREAD

**Issue by jallwork** [alexa/alexa-cookbook#81]
I have a problem creating the IAM roles (whatever they are) (Lambda function section 9)
I click Roles after selecting IAM and I only have the options Create Role (and delete role), not Create New role as shown.
If I click Create Role, I get an entirely different screen - one that says Select type of trusted entity. I don't get Select Role Type, so can't select AWS Lambda
What do I do now?

**Comment by franklin-lobb** [comment]
this could have been a result of your AWS permissions.  If this is still an issue, please reopen the issue and include a link to the specific steps/page you are following so we can try to reproduce.
