### ISSUE TITLE
lambda and text simulator succeded but echo device could not listen plan my trip skill

### ISSUE THREAD

**Issue by ramankulshrestha** [alexa/alexa-cookbook#83]
is there anything required in lambda setting

**Comment by franklin-lobb** [comment]
If the device is registered to the developer account used to create the skill, it should work on the device providing testing for that skill is enabled on the Test tab.

There is no special setting required in Lambda.  If it works in the simulator, it should work on the device (provided the above holds true).

**Comment by franklin-lobb** [comment]
closing due to age
