### ISSUE TITLE
Please add examples or more instruction for integrating AWS SES to alexa skill

### ISSUE THREAD

**Issue by tohnperfect** [alexa/alexa-cookbook#88]
Currently, the [readme](https://github.com/alexa/alexa-cookbook/tree/master/aws/Amazon-SES) is too succinct and PAGE2-4.MD is just normal instruction for building a general skill.

**Comment by franklin-lobb** [comment]
I will take a look into this.

**Comment by danagibson** [comment]
There is NO information on how to hook up a skill with the lambda function. I test the lambda function and it succeeds. I go to create the skill and since the link to setting up a lambda based skill is broken...I am not smart enough to figure it out. Please document for success.

**Comment by franklin-lobb** [comment]
Do you have a link to the code you are referencing?  The sample was taken down due to the lack of clarity.

As for a quick start on SES, you can try this one: https://aws.amazon.com/getting-started/hands-on/send-an-email/  Maybe that will get you pointed in the right direction.
