### ISSUE TITLE
Sample intent utterances with phrase types cannot consist of only slots

### ISSUE THREAD

**Issue by praveenmenon** [alexa/alexa-cookbook#89]
I had an utterance with just one slot value. No prefix or suffix, the utterance is just on slot value. It was working fine but now i am getting this error. “Sample intent utterances with phrase types cannot consist of only slots.” It was working fine before and it still works fine on another skill.

**Comment by franklin-lobb** [comment]
Since this doesn't sound like an issue with the cookbook per se, the [Alexa Developer Forum](https://forums.developer.amazon.com/spaces/23/Alexa+Skills+Kit.html) would be the best source for general help. If you're still having issues, please post there.

**Comment by franklin-lobb** [comment]
closing due to age
