### ISSUE TITLE
Update PlanMyTrip to V2

### ISSUE THREAD

**Issue by jquintozamora** [alexa/alexa-cookbook#97]
Hello,
Thanks for all the samples, 
Is there any chance to update Plan My Trip intent to ASK SDK V2?
 
https://github.com/alexa/alexa-cookbook/blob/master/handling-responses/dialog-directive-delegate/sample-nodejs-plan-my-trip/src/index.js

Thanks!

**Comment by Stefan-Markovic** [comment]
Bump.

I would really like to see Plan My Trip updated to ASK SDK V2 as well.

**Comment by wahidshafique** [comment]
👍

**Comment by franklin-lobb** [comment]
Plan my trip has been converted (and relocated within the cookbook).  Check out https://github.com/alexa/alexa-cookbook/tree/master/feature-demos/skill-demo-plan-my-trip
